let a = Math.round(Math.random() * 100)
let b = Math.round(Math.random() * 100)
alert('Sizga hozir randomdagi sonlar chiqishni boshlaydi😊😊😊')
alert(`Random son: ${a}`)
confirm(`Biz random sonni 2ga kopaytirmoqchimiz va bolmoqchimiz`)
alert(`Random orqali chiqan son: ${a} edi` + `\nBiz uni 2 ga ko'paytrib ${a * 2} sonini chiqardik` +` \nVa shu sonni 2ga bo'lib: ${a / 2} sonini chiqardik` + `\nVa shu sonni 3ga bo'lgandagi qoldiq: ${a % 3}`)
alert('Sizga hozir randomdagi sonlar chiqishni boshlaydi😎😎😎')
alert(`Random son: ${b}`)
confirm(`Biz random sonni 2ga kopaytirmoqchimiz va bolmoqchimiz`)
alert(`Random orqali chiqan son: ${b} edi `+` \nBiz uni 2 ga ko'paytrib ${b * 2} sonini chiqardik `+ `\nVa shu sonni 2ga bo'lib: ${b / 2} sonini chiqardik` +` \nVa shu sonni 3ga bo'lgandagi qoldiq: ${b % 3}`)